<?php

namespace craft\cloud;

use craft\cloud\fs\Fs;

class AssetManager extends \craft\web\AssetManager
{
    public Fs $fs;

    /**
     * @inheritDoc
     */
    public function publish($path, $options = []): array
    {
        // parent::publish($path, $options = []);
        // return [$path, $this->getPublishedUrl($path)];
    }

    /**
     * @inheritDoc
     */
    protected function publishFile($src): array
    {

        // return parent::publishFile($src); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function publishDirectory($src, $options): array
    {
        // return parent::publishDirectory($src, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getPublishedUrl($path, bool $publish = false, ?string $filePath = null): string|false
    {
        if ($publish) {
            [, $url] = $this->publish($path);
        } else {
            $url = Module::getCpResourcesUrl($path);
        }

        return $url;
    }
}
